# Generated by Django 6.0.4 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=100, verbose_name='Supplier Code')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('part_no', models.CharField(max_length=100, verbose_name='Part No')),
                ('part_description', models.TextField(verbose_name='Part Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Qty')),
                ('uom', models.CharField(choices=[('EA', 'EA - Each'), ('PC', 'PC - Piece'), ('SET', 'SET'), ('KG', 'KG'), ('M', 'M - Meter'), ('M2', 'M2 - Sq. Meter'), ('L', 'L - Liter'), ('BOX', 'BOX'), ('PKG', 'PKG - Package')], default='EA', max_length=10, verbose_name='UoM')),
                ('fc', models.BooleanField(default=False, verbose_name='FC')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('SGD', 'SGD'), ('AUD', 'AUD'), ('CHF', 'CHF')], default='USD', max_length=5, verbose_name='Currency')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Unit Price')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('date_sent', models.DateField(blank=True, null=True, verbose_name='Date Sent')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='Date Received')),
                ('lead_time', models.CharField(blank=True, max_length=100, verbose_name='Lead Time')),
                ('moq', models.PositiveIntegerField(blank=True, null=True, verbose_name='MOQ')),
                ('manufacture_part_number', models.CharField(blank=True, max_length=100, verbose_name='Manufacture Part Number')),
                ('manufacturer_name', models.CharField(blank=True, max_length=255, verbose_name='Manufacturer Name')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RFQ Entry',
                'verbose_name_plural': 'RFQ Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
