# Generated by Django 4.2.30 on 2026-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqentry',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='moq',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rfqentry',
            name='remarks',
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='alternative_part_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alternative Part No'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='alternative_parts',
            field=models.TextField(blank=True, verbose_name='Alternative Part(s)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='contact_secondary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Secondary Email'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='coo',
            field=models.CharField(blank=True, max_length=100, verbose_name='COO'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='eccn_ear99',
            field=models.CharField(blank=True, max_length=50, verbose_name='ECCN/EAR99'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='eol_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='EOL Status'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='hazmat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Hazmat (Y/N)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='hts_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='HTS Code'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='item_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Item Weight (kg)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lead Time (days)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Lot Size'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='manufacturer_address',
            field=models.TextField(blank=True, verbose_name='Manufacturer Address (Street|City|ZIP|Country)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='mfg_address_postal_cn',
            field=models.TextField(blank=True, verbose_name='Mfg Address + Postal (CN Only)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='moq_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='MOQ-1'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='moq_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='MOQ-2'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='moq_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='MOQ-3'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='order_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Order Qty'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='pic',
            field=models.CharField(blank=True, max_length=255, verbose_name='PIC'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='product_regulation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Product Regulation'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='quote_currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='quote_uom',
            field=models.CharField(blank=True, max_length=20, verbose_name='UOM'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='russian_steel_confirmation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Russian Steel Confirmation'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='ship_lead_time_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ship Lead Time (days)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='uflpa_compliance',
            field=models.CharField(blank=True, max_length=100, verbose_name='UFLPA Compliance Statement (CN Only)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='uflpa_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='UFLPA Expiry Date'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='uflpa_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='UFLPA Start Date'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='un_sds_msds',
            field=models.CharField(blank=True, max_length=255, verbose_name='UN# · SDS/MSDS'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='unit_price_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Unit Price 1'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='unit_price_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Unit Price 2'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='unit_price_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Unit Price 3'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='usmca_certificate',
            field=models.CharField(blank=True, max_length=100, verbose_name='USMCA Certificate (CA/MX Only)'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='usmca_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='USMCA Expiry Date'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='usmca_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='USMCA Start Date'),
        ),
        migrations.AddField(
            model_name='rfqentry',
            name='volume_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='rfqentry',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='rfqentry',
            name='part_description',
            field=models.TextField(blank=True, verbose_name='Part Description'),
        ),
        migrations.AlterField(
            model_name='rfqentry',
            name='uom',
            field=models.CharField(blank=True, max_length=20, verbose_name='UOM'),
        ),
    ]
