# Generated by Django 4.2.29 on 2026-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_rfqentry_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfqentry',
            options={'ordering': ['id'], 'verbose_name': 'RFQ Entry', 'verbose_name_plural': 'RFQ Entries'},
        ),
        migrations.AlterField(
            model_name='rfqentry',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='rfqentry',
            name='contact_secondary_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Secondary Email'),
        ),
    ]
