# Generated by Django 4.2.30 on 2026-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_rfqentry_options_alter_rfqentry_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqentry',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Comments'),
        ),
    ]
