# Generated by Django 4.2.29 on 2026-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rfqentry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqentry',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status'),
        ),
    ]
