# Generated by Django 4.2.30 on 2026-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rfqentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqentry',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
    ]
