# Generated by Django 4.2.30 on 2026-04-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_rfqentry_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=100, unique=True, verbose_name='Supplier Code')),
                ('supplier_company_name', models.CharField(max_length=255, verbose_name='Supplier Company Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['supplier_code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PO Confirmation', 'PO Confirmation'), ('RFQ - Request for Quotation', 'RFQ - Request for Quotation'), ('Returns & Claims', 'Returns & Claims'), ('Quality', 'Quality'), ('Accounts Receivable', 'Accounts Receivable'), ('Escalation', 'Escalation')], max_length=100, verbose_name='Contact Type')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('role_title', models.CharField(blank=True, max_length=255, verbose_name='Role / Title')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tracker.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Contact',
                'verbose_name_plural': 'Supplier Contacts',
                'ordering': ['contact_type', 'id'],
            },
        ),
    ]
