# Generated by Django 4.2.30 on 2026-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_supplier_suppliercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqentry',
            name='rfq_sent',
            field=models.CharField(blank=True, max_length=10, verbose_name='RFQ Sent'),
        ),
    ]
