# Generated by Django 4.2.30 on 2026-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rfq_sent_default_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqentry',
            name='pr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='PR'),
        ),
    ]
